### ISSUE TITLE
Stop Gradient When Screen is Off

### ISSUE THREAD

**Issue by searchy2** [Mursaat/AnimatedGradientTextView#2]
The gradient should stop animating when the screen is off to save battery. Currently, the gradient animation continues with the screen off and drains battery.

**Comment by Mursaat** [comment]
With v0.0.5, it should stop the animation in onScreenStateChanged when screenState == SCREEN_STATE_OFF

**Comment by searchy2** [comment]
Wow, thank you so much! This is an amazing library and SOOO beautiful :rose: 
I must apologize for the tone in my issues reports. I made them as TODO items to remind me to fix those issues. I did not mean to be so abrupt! 
This library is so wonderful. Thank you for sharing it!

**Comment by Mursaat** [comment]
Thanks 😉

**Comment by searchy2** [comment]
You rock! The AnimatedGradientTextView no longer uses CPU when the screen is off. Amazing work!
