### ISSUE TITLE
Customize MAX FPS

### ISSUE THREAD

**Issue by searchy2** [Mursaat/AnimatedGradientTextView#3]
Allow the user to customize the MAX FPS of the gradient text including reducing the FPS. Currently, the FPS is set to 60 which demands massive CPU usage. Reducing the FPS to 30 or 24 could cut the CPU usage by half.

**Comment by Mursaat** [comment]
Hello. I added maxFPS attribute, it should be okay.

**Comment by searchy2** [comment]
Absolutely amazing! Reducing the FPS to 24 from 60 decreased CPU usage from 40% to 5%!!!
That's an 800% performance improvement with no noticeable change in visual quality. Thanks for doing this feature enhancement. Just wow :hugs:
